####################################################################################################
# < Doflake > Themes
####################################################################################################
# ä¸»é¢˜ç®€ä»‹
# 
#   ä¸»é¢˜å : Doflake 
#     åå­—æ€è·¯æ¥æº : [å…ƒç¥–]Dove & [å…ƒç¥–]Beelake åå­—åˆæˆ (Dof & Lake)
#
#   ç›®å‰å­˜åœ¨ 2 å å¼€å‘äººå‘˜  ( --ğŸ˜æ¬¢è¿åŠ å…¥ğŸ˜-- )
#     1. [å…ƒç¥–] Dove : å®ç°ä¸»é¢˜ (åŠŸèƒ½ , æ ·å¼ , å¸ƒå±€)
#     2. [å…ƒç¥–] Beelake : æ–‡ç«  , æŸ¥è¯¢èµ„æ–™ , æ‰¾æ–°åŠŸèƒ½
#   
#   ä¸»é¢˜åšå®¢ : https://doflake.github.io/
#     æ³¨é‡Š : ä¸»é¢˜åšå®¢ ä¸æ­¢æœ‰ ä¸»é¢˜ç›¸å…³å†…å®¹ è¿˜æœ‰ Doflake çš„å…¶ä»–æ–‡ç«  
#            ä¸»é¢˜ç›¸å…³å†…å®¹ å‡åœ¨ ä¸»é¢˜æ–‡æ¡£ ä¸­
#   ä¸»é¢˜æ–‡æ¡£ : https://doflake.github.io/doflake-document/
#     æ³¨é‡Š : åŒ…å« "ä¸»é¢˜ç®€ä»‹" "ä¸»é¢˜ä¸‹è½½" "ä¸»é¢˜é£Ÿç”¨" "ä¸»é¢˜å‘å±•å²" ç­‰å†…å®¹ 
#
# å…¶ä»–
#
#   å¤šå¤šæ”¯æŒï¼Œååˆ†æ„Ÿè°¢
#   å¦‚æœ æœ‰å¥½çš„æè®® Doflake éƒ½ä¼šå¬çš„
#
# -------------------------------------------------------------------------------------------------- 

####################################################################################################
# Basic Settings åŸºç¡€è®¾ç½®
####################################################################################################
basic:
  
## Info åŸºæœ¬ä¿¡æ¯
# **************************|*********************************
# info:                     |    åŸºæœ¬ä¿¡æ¯ ç›¸å…³
#  title:                   |    ç½‘é¡µæ ‡é¢˜
#  favicon:                 |    ç½‘é¡µå›¾æ ‡ 
# **************************|*********************************
  info:
   title: Doflake
   favicon: https://cdn.jsdelivr.net/gh/doflake/Picture/Favicon/1.jpg

## Card é¦–é¡µå¡ç‰‡
# **************************|*********************************
# card:                     |    é¦–é¡µå¡ç‰‡ ç›¸å…³
#   title:                  |    å¡ç‰‡æ ‡é¢˜
#   image:                  |    å¡ç‰‡å›¾ç‰‡
#   background-color:       |    èƒŒæ™¯é¢œè‰²
#   text-color:             |    æ ‡é¢˜é¢œè‰²
# **************************|*********************************
  card:
    title: ã€Œ Doflake ã€
    image: https://cdn.jsdelivr.net/gh/doflake/Picture/Card/Avatar-Dove.jpg
    background-color: 0,0,0
    text-color: 255,0,255
    
## Body èƒŒæ™¯
# **************************|*********************************
# body:                     | 
#   background-color:       |
# **************************|*********************************
  body:
    background-color: "#CBCCFF"
       
## Menu å¯¼èˆªæ 
# **************************|*********************************
# menu:                     |
#   [AA]:                   |   å¯¼èˆªæ ä¸­ç»„ä»¶åç§°
#     name:                 |   å†…å®¹
#     link:                 |   è·³è½¬é“¾æ¥  
# **************************|*********************************
  menu:
   Home: 
     name: ä¸»é¡µ
     link: /
   Document:
     name: ä¸»é¢˜æ–‡æ¡£
     link: /doflake-document/
   Archives:
     name: å½’æ¡£
     link: /archives/
   Github: 
     name: Github
     link: https://github.com/doflake/
   FunnyBaidu:
     name: åº¦å¨˜
     link: /Funny-Baidu

## Mathjax æ¸²æŸ“å…¬å¼
# **************************|*********************************
# ä½¿ç”¨:
#   ç§»é™¤ marked æ¸²æŸ“å™¨ npm uninstall hexo-renderer-marked --save
#   å®‰è£… kramed æ¸²æŸ“å™¨ npm install hexo-renderer-kramed --save
# Attention : å¼€å¯åé»˜è®¤ä¸ºæ‰€æœ‰å…¬å¼å…¨éƒ¨æ¸²æŸ“ (åŒ…æ‹¬ æ ‡é¢˜ ç­‰)
# **************************|*********************************
  mathjax:
   enable: true

# -------------------------------------------------------------------------------------------------- < End Basic Setting >

####################################################################################################
# Layout å¸ƒå±€
####################################################################################################
layout:

## Index_post ä¸»é¡µæ–‡ç« å—
# **************************|*********************************
# index_post:               |   ä¸»é¡µæ–‡ç« å— ç›¸å…³
#   container:              |   å•ä¸ªå®¹å™¨ ç›¸å…³
#     left:                 |   ç¦»å·¦ä¾§
#     top:                  |   ç¦»ä¸Šæ–¹
#     max-width:            |   æ–‡ç« æœ€å¤§å®½åº¦
#     background-color:     |   èƒŒæ™¯é¢œè‰²
#   title:                  |   æ–‡ç« æ ‡é¢˜
#     color:                |   æ ‡é¢˜é¢œè‰²
#     underline:            |   ä¸‹åˆ’çº¿ ç›¸å…³
#       under:              |   ç¦»æ–‡å­—è·ç¦»
#       time:               |   åŠ¨ç”»æ€»æ—¶é•¿
#       height:             |   ä¸‹åˆ’çº¿ç²—ç»†
# **************************|*********************************
    index_post:
      container:
        left: 1vw
        top: 40px
        max-width: 60vw
        background-color: "#FFF5F9"
      title:
        color: "#EC87E4"
        underline:
          under: -2px
          time: 0.4s
          height: 2px
      
# -------------------------------------------------------------------------------------------------- < End Layout >

####################################################################################################
# Meta ç»„ä»¶
####################################################################################################
meta:

## Totop å‰å¾€é¡¶ç«¯
# **************************|*********************************  
# totop:                    |   å‰å¾€é¡¶ç«¯
#   enable:                 |   æ˜¯å¦å¯ç”¨
#   url:                    |   å›¾ç‰‡åœ°å€
# **************************|*********************************  
  totop: 
    enable: true
    url: https://cdn.jsdelivr.net/gh/doflake/Picture/ToTop/Rem 100x100.png

## Clock æ—¶é’Ÿ
# **************************|*********************************  
# clock:                    |   éœ“è™¹ç¯ æ—¶é’Ÿ
#   enable:                 |   æ˜¯å¦å¯ç”¨
#   layout:                 |   æ ·å¼
#     size:                 |   æ—¶é’Ÿ å¤§å°
#     fill:                 |   æ—¶é’Ÿ å­—ä½“é¢œè‰²
#     stroke_width:         |   éœ“è™¹ç¯å¸¦ å®½åº¦
#     time:                 |   éœ“è™¹ç¯å¸¦ èµ°å®Œä¸€æ¬¡æ—¶é•¿
# **************************|*********************************  
  clock:
    enable: true
    layout:
      size: 45px
      fill: "#000000"
      stroke_width: 3px
      time: 8

# -------------------------------------------------------------------------------------------------- < End Meta >
